autolabeler:
  - label: 'patch'
    body:
      - '/\[x] Patch/gm'
  - label: 'minor'
    body:
      - '/\[x] Minor/gm'
  - label: 'major'
    body:
      - '/\[x] Major/gm'
  - label: 'bugfix'
    body:
      - '/\[x] Bug Fix/gm'
  - label: 'documentation'
    body:
      - '/\[x] Documentation/gm'
  - label: 'feature'
    body:
      - '/\[x] Feature/gm'
  - label: 'enhancement'
    body:
      - '/\[x] New Component/gm'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES